#!/bin/sh

set -e
set -u

IMAGE_DIR="/workdir/src/images/"
IMAGE_TS="/workdir/src/images/images.ts"

cat <<END >| "${IMAGE_TS}"
// DON'T EDIT!"
// This file is automatically generated by gen-scripts/images.sh" 
// To update this file, use gen-scripts/images.sh"

END

{
    for IMG in $(ls "${IMAGE_DIR}"| grep ".jpg"); do
        VAR_NAME=$(echo "${IMG}" | sed -e 's/\.jpg//g')
        echo "import ${VAR_NAME} from \"../images/${IMG}\";"
    done
    echo ""
} >> "${IMAGE_TS}"

{
    echo "let images = new Map<string, string>();"
    for IMG in $(ls "${IMAGE_DIR}"| grep ".jpg"); do
        VAR_NAME=$(echo "${IMG}" | sed -e 's/\.jpg//g')
        echo "images.set(\"${VAR_NAME}\", ${VAR_NAME} as string);"
    done
    echo ""
} >> "${IMAGE_TS}"

cat <<END >> "${IMAGE_TS}"
export function getImage(name:string): string | undefined {
    return images.get(name);
}
END

