// DON'T EDIT!"
// This file is automatically generated by gen-scripts/images.sh" 
// To update this file, use gen-scripts/images.sh"

import IMG_1636 from "../images/IMG_1636.jpg";
import IMG_1643 from "../images/IMG_1643.jpg";
import IMG_1654 from "../images/IMG_1654.jpg";
import IMG_1673 from "../images/IMG_1673.jpg";
import IMG_1674 from "../images/IMG_1674.jpg";
import IMG_1676 from "../images/IMG_1676.jpg";
import IMG_1678 from "../images/IMG_1678.jpg";
import IMG_1679 from "../images/IMG_1679.jpg";
import IMG_1681 from "../images/IMG_1681.jpg";
import IMG_1683 from "../images/IMG_1683.jpg";
import IMG_1735 from "../images/IMG_1735.jpg";
import IMG_1744 from "../images/IMG_1744.jpg";
import IMG_1748 from "../images/IMG_1748.jpg";
import IMG_1751 from "../images/IMG_1751.jpg";
import IMG_1753 from "../images/IMG_1753.jpg";
import IMG_1776 from "../images/IMG_1776.jpg";
import IMG_1792 from "../images/IMG_1792.jpg";
import IMG_1794 from "../images/IMG_1794.jpg";
import IMG_1796 from "../images/IMG_1796.jpg";
import IMG_1797 from "../images/IMG_1797.jpg";
import IMG_1798 from "../images/IMG_1798.jpg";
import IMG_1803 from "../images/IMG_1803.jpg";
import IMG_1805 from "../images/IMG_1805.jpg";
import IMG_1807 from "../images/IMG_1807.jpg";
import IMG_1808 from "../images/IMG_1808.jpg";
import IMG_1812 from "../images/IMG_1812.jpg";
import IMG_1815 from "../images/IMG_1815.jpg";
import IMG_1818 from "../images/IMG_1818.jpg";
import IMG_1822 from "../images/IMG_1822.jpg";
import IMG_1824 from "../images/IMG_1824.jpg";
import IMG_1825 from "../images/IMG_1825.jpg";
import IMG_1826 from "../images/IMG_1826.jpg";
import IMG_1835 from "../images/IMG_1835.jpg";
import IMG_1837 from "../images/IMG_1837.jpg";

let images = new Map<string, string>();
images.set("IMG_1636", IMG_1636 as string);
images.set("IMG_1643", IMG_1643 as string);
images.set("IMG_1654", IMG_1654 as string);
images.set("IMG_1673", IMG_1673 as string);
images.set("IMG_1674", IMG_1674 as string);
images.set("IMG_1676", IMG_1676 as string);
images.set("IMG_1678", IMG_1678 as string);
images.set("IMG_1679", IMG_1679 as string);
images.set("IMG_1681", IMG_1681 as string);
images.set("IMG_1683", IMG_1683 as string);
images.set("IMG_1735", IMG_1735 as string);
images.set("IMG_1744", IMG_1744 as string);
images.set("IMG_1748", IMG_1748 as string);
images.set("IMG_1751", IMG_1751 as string);
images.set("IMG_1753", IMG_1753 as string);
images.set("IMG_1776", IMG_1776 as string);
images.set("IMG_1792", IMG_1792 as string);
images.set("IMG_1794", IMG_1794 as string);
images.set("IMG_1796", IMG_1796 as string);
images.set("IMG_1797", IMG_1797 as string);
images.set("IMG_1798", IMG_1798 as string);
images.set("IMG_1803", IMG_1803 as string);
images.set("IMG_1805", IMG_1805 as string);
images.set("IMG_1807", IMG_1807 as string);
images.set("IMG_1808", IMG_1808 as string);
images.set("IMG_1812", IMG_1812 as string);
images.set("IMG_1815", IMG_1815 as string);
images.set("IMG_1818", IMG_1818 as string);
images.set("IMG_1822", IMG_1822 as string);
images.set("IMG_1824", IMG_1824 as string);
images.set("IMG_1825", IMG_1825 as string);
images.set("IMG_1826", IMG_1826 as string);
images.set("IMG_1835", IMG_1835 as string);
images.set("IMG_1837", IMG_1837 as string);

export function getImage(name:string): string | undefined {
    return images.get(name);
}
